name: 'rss-news Feed'

on:
  push:
    branches:
      - main
  schedule:
    - cron: ' 30 * * * * '

jobs:
  feed-processor:
    name: rss-news Feed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Build RSS
        run: node index.js
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          token: ${{ secrets.NEWS_TOKEN}}
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch
          clean-exclude: |
            audio/*.mp3
